package com.company.employeemanager.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing an employee in the system.
 * Audit fields ({@code createdAt}, {@code updatedAt}) are managed by Spring Data JPA Auditing.
 */
@Entity
@Table(name = "employees")
@EntityListeners(AuditingEntityListener.class)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Employee {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Employee's first name. Cannot be null, max 100 characters. */
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    /** Employee's last name. Cannot be null, max 100 characters. */
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /** Unique email address of the employee. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** Optional phone number. Max 20 characters. */
    @Column(name = "phone", length = 20)
    private String phone;

    /** Department the employee belongs to. */
    @Column(name = "department", nullable = false, length = 100)
    private String department;

    /** Job title of the employee. */
    @Column(name = "job_title", nullable = false, length = 100)
    private String jobTitle;

    /** Employee's salary. Must be a positive value. */
    @Column(name = "salary", nullable = false, precision = 15, scale = 2)
    private BigDecimal salary;

    /** Date when the employee was hired. */
    @Column(name = "hire_date", nullable = false)
    private LocalDate hireDate;

    /** Name of the employee's reporting manager. Optional field. */
    @Column(name = "reporting_manager", length = 200)
    private String reportingManager;

    /** Current employment status. Defaults to {@link EmployeeStatus#ACTIVE}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private EmployeeStatus status = EmployeeStatus.ACTIVE;

    /** Timestamp when the record was first created. Not updatable after creation. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp when the record was last modified. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
